ComartHeijn/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComartHeijn.Data;
using ComartHeijn.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace ComartHeijn.Controllers
{
    public class CheckoutController : Controller
    {
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public CheckoutController(ApplicationDbContext context,
            UserManager<ApplicationUser> userMan)
        {
            _context = context;
            _userManager = userMan;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            CheckoutViewModel cvm = new CheckoutViewModel();

            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);

            cvm.Address = user.Straatnaam;
            cvm.City = user.Woonplaats;
            cvm.Housenumber = user.Huisnummer.ToString();
            cvm.Phonenumber = user.PhoneNumber;
            cvm.Zipcode = user.Postcode;
            List<DeliverySlots> deliverySlots = new List<DeliverySlots>();
            var deliveries = _context.DeliverySlots.ToList();
            cvm.DeliverySlots = deliveries;
            //ViewBag["DeliverySlot"] = new SelectList(cvm.DeliverySlots);





            List<CartItem> cart = new List<CartItem>();

            string cartString = HttpContext.Session.GetString("cart");
            if (cartString != null)
                cart = JsonConvert.DeserializeObject<List<CartItem>>(cartString);


            List<CartItemViewModel> cartvm = new List<CartItemViewModel>();

            double totalPrice = 0;

            foreach (CartItem ci in cart)
            {
                CartItemViewModel civm = new CartItemViewModel();

                civm.ProductId = ci.ProductId;
                civm.Amount = ci.Amount;

                Product p = _context.Product.Find(ci.ProductId);

                civm.Title = p.Title;
                civm.Price = Convert.ToDouble(p.Price);
                civm.Image = p.Image;

                totalPrice += ci.Amount * Convert.ToDouble(p.Price);

                cartvm.Add(civm);
            }

            cvm.CartItems = cartvm;
            cvm.TotalPrice = totalPrice;

            return View(cvm);
        }
        // GET: CheckOut/Delete/2
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var CartItem = await _context.CartItem
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (CartItem == null)
            {
                return NotFound();
            }

            return View("Index");
        }

        // POST: CheckOut/Delete/2
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cartitem = await _context.CartItem.FindAsync(id);
            _context.CartItem.Remove(cartitem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Index(CheckoutViewModel model)
        {
            Order order = new Order();
            order.Address = model.Address;
            order.City = model.City;
            order.Name = model.Name;
            order.Phonenumber = model.Phonenumber;
            order.Zipcode = model.Zipcode;
            order.Housenumber = model.Housenumber;

            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);

            order.User = user;

            order.OrderLines = new List<OrderLine>();

            List<CartItem> cart = new List<CartItem>();

            string cartString = HttpContext.Session.GetString("cart");
            if (cartString != null)
                cart = JsonConvert.DeserializeObject<List<CartItem>>(cartString);

            foreach (CartItem cartItem in cart)
            {
                Product product = _context.Product.Find(cartItem.ProductId);

                OrderLine orderLine = new OrderLine();
                orderLine.Amount = cartItem.Amount;
                orderLine.Price = Convert.ToDouble(product.Price);
                orderLine.ProductId = cartItem.ProductId;

                order.OrderLines.Add(orderLine);
            }

            try
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
            }
            catch (Exception e)
            {
                return StatusCode(500);
            }

            return View("Confirm");


        }
        // Verwijder uit winkelwagen
        public IActionResult RemoveFromCart(int id)
        {
            List<CartItem> cart = new List<CartItem>();

            string cartString = HttpContext.Session.GetString("cart");
            if (cartString != null)
            {
                cart = JsonConvert.DeserializeObject<List<CartItem>>(cartString);
            }

            var product = cart.FirstOrDefault(p => p.ProductId == id);
            product.Amount--;

            if (product.Amount < 1)
            {
                cart.Remove(product);

            }
            cartString = JsonConvert.SerializeObject(cart);

            HttpContext.Session.SetString("cart", cartString);
            //Zorgt ervoor dat de klant niet kan bestellen zonder producten in zijn wagen.
            if (cart.Count < 1)
            {
                return RedirectToAction("Index", "Producten");

            }

            return RedirectToAction("Index");
        }
    }
}

ComartHeijn/Controllers/ProductenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ComartHeijn.Data;
using ComartHeijn.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using ComartHeijn.Migrations;

namespace ComartHeijn.Controllers
{
    public class ProductenController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductenController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        [HttpGet]
        public IActionResult Categorie(int? id)
        {
            List<Product> producten = new List<Product>();
            var producties = _context.Product.ToList();
            var cat = _context.Category.ToList();

            foreach(var Producties in producties)
            {
                if(Producties.CategoryId == id){
                    var prod = Producties.Id;
                    var products = _context.Product.Where(a => a.Category.Id == id);
                    producten = products.ToList();
                }

            }            
            return View(producten);
        }

        // Aantal verhogen
        public IActionResult IncreaseAmount(int id) 
        {
            List<CartItem> cart = new List<CartItem>();

            string cartString = HttpContext.Session.GetString("cart");
            if (cartString != null) 
            {
                cart = JsonConvert.DeserializeObject<List<CartItem>>(cartString);
            }

            var product = cart.FirstOrDefault(p => p.ProductId == id);
            product.Amount++;

            cartString = JsonConvert.SerializeObject(cart);

            HttpContext.Session.SetString("cart", cartString);

            return RedirectToAction("ShowCart");
        }


        // Voeg toe aan winkelwagen
        public IActionResult AddToCart(int id)
        {
            List<CartItem> cart = new List<CartItem>();

            string cartString = HttpContext.Session.GetString("cart");
            if (cartString != null)
            {
                cart = JsonConvert.DeserializeObject<List<CartItem>>(cartString);
            }

            CartItem item = new CartItem { ProductId = id, Amount = 1 };
            cart.Add(item);

            cartString = JsonConvert.SerializeObject(cart);

            HttpContext.Session.SetString("cart", cartString);

            return RedirectToAction("Showcart");
        }

        // Verwijder uit winkelwagen
        public IActionResult RemoveFromCart(int id)
        {
            List<CartItem> cart = new List<CartItem>();

            string cartString = HttpContext.Session.GetString("cart");
            if (cartString != null)
            {
                cart = JsonConvert.DeserializeObject<List<CartItem>>(cartString);
            }

            var product = cart.FirstOrDefault(p => p.ProductId == id);
            product.Amount--;

            if (product.Amount < 1)
            {
                cart.Remove(product);
                
            }
            cartString = JsonConvert.SerializeObject(cart);

            //Zorgt ervoor dat de klant niet kan bestellen zonder producten in zijn wagen.
            if (cart.Count < 1)
            {
                return RedirectToAction("Index", "Producten");

            }

            HttpContext.Session.SetString("cart", cartString);

            return RedirectToAction("ShowCart");
        }
    

        // Laat winkelwagen zien
        public IActionResult ShowCart()
        {
            List<CartItem> cart = new List<CartItem>();

            string cartString = HttpContext.Session.GetString("cart");
            if (cartString != null)
            {
                cart = JsonConvert.DeserializeObject<List<CartItem>>(cartString);
            }

            List<CartItemViewModel> civm = new List<CartItemViewModel>();

            foreach (CartItem ci in cart)
            {

                
                Product product = _context.Product.Find(ci.ProductId);
                CartItemViewModel item = new CartItemViewModel();
        
                item.ProductId = ci.ProductId;
                item.Amount = ci.Amount;
                item.Title = product.Title;
                item.Image = product.Image;
                item.Price = Convert.ToDouble(product.Price);

                
                civm.Add(item);
            }

            return View(civm);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EAN,Title,Brand,Shortdescription,Fulldescription,Price,Image,Weight,Category,Subcategory,Subsubcategory")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EAN,Title,Brand,Shortdescription,Fulldescription,Price,Image,Weight,Subcategory,Subsubcategory")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.Id == id);
        }
    }
}

ComartHeijn/Views/Producten/Categorie.cshtml
@model IEnumerable<ComartHeijn.Models.Product>

@{
    ViewData["Title"] = "Index";
}




<div class="customcontainer">

    <br />
    <h1>Producten</h1>
    @if (TempData["Message"] != null)
    {
        <div id="helpdiv" class="alert alert-success" role="alert" style="

  position: fixed;
  top: 50%;
  left:0px;
  -webkit-transform: translateY(-50%);
  -ms-transform: translateY(-50%);
  transform: translateY(-50%);


">
            @TempData["Message"]
        </div>
        <script type="text/javascript">
            // close the div in 5 secs
            window.setTimeout("closeHelpDiv();", 1600);

            function closeHelpDiv() {
                document.getElementById("helpdiv").style.display = " none";
            }
        </script>
    }




    <hr />
    <br />

    <div class="container">
        <div class="row" style="margin:0">
            @foreach (var item in Model)
            {
                <div class="col-md-3" id="@("product" + @item.Id)" style="margin:0px; padding:0px; text-align: center; align-content:center; text-decoration: none;">
                    <a asp-action="Details" asp-route-id="@item.Id" style="text-decoration: none;">

                        <div class="card" style="height:450px; text-align: center; align-content:center">
                            <div style=" width:100%; text-align: center; align-content:center">
                                <img class="productfoto" style="margin-top:20px; width:99%;" src="@item.Image">
                            </div>
                            <div style="width:100%; height:20px; margin-bottom:20px;">
                                <p>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </p>
                            </div>
                            <div class="card-body">
                                <p>&euro;@Html.DisplayFor(modelItem => item.Price)</p>
                                <div>
                                    <a asp-action="AddToCart" class="btn btn-success" asp-route-id="@item.Id">
                                        In winkelwagen
                                    </a>


                                </div>

                            </div>
                        </div>

                    </a>
                </div>
            }
        </div>

    </div>
</div>



@*@section scripts{
        <script>
            $(function () {
                $("#basic-text1").click(function () {
                    $("Form").submit();
                })
            });
        </script>
    }*@

ComartHeijn/Views/Producten/Create.cshtml
@model ComartHeijn.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EAN" class="control-label"></label>
                <input asp-for="EAN" class="form-control" />
                <span asp-validation-for="EAN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Shortdescription" class="control-label"></label>
                <input asp-for="Shortdescription" class="form-control" />
                <span asp-validation-for="Shortdescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fulldescription" class="control-label"></label>
                <input asp-for="Fulldescription" class="form-control" />
                <span asp-validation-for="Fulldescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subcategory" class="control-label"></label>
                <input asp-for="Subcategory" class="form-control" />
                <span asp-validation-for="Subcategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subsubcategory" class="control-label"></label>
                <input asp-for="Subsubcategory" class="form-control" />
                <span asp-validation-for="Subsubcategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ComartHeijn/Views/Producten/Delete.cshtml
@model ComartHeijn.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EAN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EAN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Shortdescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Shortdescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fulldescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fulldescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subcategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subcategory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subsubcategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subsubcategory)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ComartHeijn/Views/Producten/Details.cshtml
@model ComartHeijn.Models.Product

@{
    ViewData["Title"] = "Details";
}

<div class="container">
  <div class="row">
      <div class="col">
          <img width="400" src="@Html.DisplayFor(model => model.Image)" />
      </div>
      <div class="col">
          <div>
                <hr />
              <h4>@Html.DisplayFor(model => model.Title)</h4>
              <h5>@Html.DisplayFor(model => model.Brand)</h5>
              <hr />
              @Html.DisplayFor(model => model.Shortdescription)
              <br />
              <hr />
              <p>&euro;@Html.DisplayFor(model => model.Price)</p>
              <a class="btn btn-primary" asp-action="AddToCart" asp-route-id="@Model.Id">Toevoegen aan winkelwagen</a><br />
          </div>
  </div>
    
  <div>

      <h2>Beschrijving</h2>
      <hr />
      @Html.DisplayFor(model => model.Fulldescription)

        <hr />
      <a asp-action="Index">Terug</a>
  </div>

ComartHeijn/Views/Producten/Edit.cshtml
@model ComartHeijn.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="EAN" class="control-label"></label>
                <input asp-for="EAN" class="form-control" />
                <span asp-validation-for="EAN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Shortdescription" class="control-label"></label>
                <input asp-for="Shortdescription" class="form-control" />
                <span asp-validation-for="Shortdescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fulldescription" class="control-label"></label>
                <input asp-for="Fulldescription" class="form-control" />
                <span asp-validation-for="Fulldescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subcategory" class="control-label"></label>
                <input asp-for="Subcategory" class="form-control" />
                <span asp-validation-for="Subcategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subsubcategory" class="control-label"></label>
                <input asp-for="Subsubcategory" class="form-control" />
                <span asp-validation-for="Subsubcategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ComartHeijn/Views/Producten/Index.cshtml
@model IEnumerable<ComartHeijn.Models.Category>

@{
    ViewData["Title"] = "Index";
}

    <h1>Categorieën</h1>
<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-sm-6">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="~/banners/@Html.DisplayFor(modelItem => item.BannerUrl)" alt="Card image cap">
                <div class="card-body">
                    <a asp-action="Categorie" asp-route-id="@item.Id" class="card-title">@Html.DisplayFor(modelItem => item.Naam)</a>
                    @*<h5 class="card-title">@Html.DisplayFor(modelItem => item.Naam)</h5>*@
                    @*<p class="card-text">@Html.DisplayFor(modelItem => item.Datum) in @Html.DisplayFor(modelItem => item.Categorie)</p>*@
                </div>
            </div>
        </div>
    }
</div>

ComartHeijn/Views/Producten/ShowCart.cshtml
@model IEnumerable<ComartHeijn.Models.CartItemViewModel>

@{
    ViewData["Title"] = "ShowCart";
}

<h1>Winkelwagen</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.ProductId">@Html.DisplayFor(modelItem => item.Title)</a>
            </td>
            <td>
                <img src="@item.Image" height="64" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
                <a class="btn btn-sm" asp-action="IncreaseAmount" asp-route-id="@item.ProductId">+</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPrice)
            </td>
            <td>
                <a class="btn btn-primary" asp-action="RemoveFromCart" asp-route-id="@item.ProductId">Verwijderen uit winkelwagen</a><br />
            </td>
        </tr>
}
    </tbody>
</table>
<a class="btn btn-primary text-light" asp-action="Index" asp-controller="Checkout">Checkout</a>